### PR TITLE
Internal preprocessing, fixing canny errors

### PR DESCRIPTION
**Pull request by davidfuhry**
I merged main and resolved some merge conflicts so that the script runs without errors.

This generally seems like a good approach to me, there are two things I think should be adressed before we merge:

* The functions should be somewhere in the image section of the scripts, not under helpers (as these are methods used in multiple places or helpers not generally used in processing)
* When running with default settings, there are still some issues with interconnected notes, though I did not check the configuration, so this might be on me?

E.g. for the second issue (using `data/test_image/test_1.jpg`):

image
image

### CODE REVIEW

**Comment by robebe** [comment]
there are also problematic sections with test_2.jpg and test_3.jpg:
Screen Shot 2021-04-12 at 12 49 59
Screen Shot 2021-04-12 at 12 50 36
ng)

**Comment by robebe** [comment]
CV2 morphological transformation is our friend:

Black and white (original preprocessing):
Screen Shot 2021-04-12 at 17 18 08

Erosion of edges with 3x3 kernel:
Screen Shot 2021-04-12 at 17 18 28

Noise reduction with "opening" (erosion followed by dilation):
Screen Shot 2021-04-12 at 17 18 37

although this doesn't solve the problematic edge detection on test_img2

**Comment by robebe** [comment]
... and test_img1

**Comment by davidfuhry** [comment]
Snap, that's annoying. Looks good though.

I ran some tests and I found that I had to turn down the brightness quite aggressively for decent note separation (80 seems a good value, and I think the scale is percent as decreasing by 100 yielded a black picture). Increasing the contrast was more of a quality of life thing and there actually are some advantages to not turn it too high. So maybe there's some gains to be made in that direction?

As a reference, this is `test_2.jpg` after `convert test_2.jpg -brightness-contrast -80x50 -morphology EdgeIn Octagon test_2_im.TIFF`:

test_2_im

Which (using the `--skip-canny` switch in #19) yields these detected notes:

test_2_shapes

Unfortunately it also breaks the center detection algorithm which in turn breaks track detection which in turn breaks everything else... So if this could be avoided by not using ImageMagick that would be a welcome aid.

PS: Spamming the `+contrast` parameter in ImageMagick enough yields some rather fancy things:
image

**Comment by davidfuhry** [comment]
Just took a quick look at some of the final images, and as these look much better than the current test images, we might be in luck and have this just work without much modification (though I still am somewhat baffled why ImageMagic produces results that much better).

Will replace the test images with the new ones later today.

**Comment by davidfuhry** [comment]
As this got somewhat convoluted we merge this now and refactor some components later on to prevent even more chaos in this branch.

**Pull request merged**
